# Force deploy: 0

name: Run tests and deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/on-push.yml'
      - 'fbase/*.rules'
      - 'fbase/*.json'
      - 'fbase/functions/**'
      - 'client/package.json'

jobs:
  run_firebase_tests:
    name: Tests
    uses: webhookbuddy/webhookbuddy/.github/workflows/run-firebase-tests.yml@dev
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
  # Job to run change detection: https://github.com/dorny/paths-filter#examples
  changes_dev:
    needs: run_firebase_tests
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/dev'}}
    name: Changes dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Set job outputs to values from filter step
    outputs:
      firebase: ${{steps.filter.outputs.firebase}}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'dev'
          filters: |
            firebase:
              - '**/on-push.yml'
              - 'fbase/*.rules'
              - 'fbase/*.json'
              - 'fbase/functions/**'
  changes_main:
    needs: run_firebase_tests
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    name: Changes main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Set job outputs to values from filter step
    outputs:
      firebase: ${{steps.filter.outputs.firebase}}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            firebase:
              - '**/on-push.yml'
              - 'fbase/*.rules'
              - 'fbase/*.json'
              - 'fbase/functions/**'
  deploy_firebase_dev:
    needs: changes_dev
    if: ${{needs.changes_dev.outputs.firebase == 'true'}}
    name: DEV
    uses: webhookbuddy/webhookbuddy/.github/workflows/deploy-firebase.yml@dev
    with:
      projectAlias: dev
      fromEmail: webhookbuddy-dev@jobcast.net
      unsubscribeUrlFormat: https://app-dev.webhookbuddy.com/unsubscribes/{email}?hash={hash}
      inviteUrlFormat: https://app-dev.webhookbuddy.com/invites/{endpointId}?email={email}&hash={hash}
      smtpHost: smtp.mailgun.org
      smtpPort: 587
      smtpAuthUser: postmaster@mg.webhookbuddy.com
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
      signatureKey: ${{secrets.SIGNATURE_KEY_DEV}}
      smtpAuthPass: ${{secrets.SMTP_AUTH_PASS}}
  deploy_firebase_prod:
    needs: changes_main
    if: ${{needs.changes_main.outputs.firebase == 'true'}}
    name: PROD
    uses: webhookbuddy/webhookbuddy/.github/workflows/deploy-firebase.yml@dev
    with:
      projectAlias: prod
      fromEmail: webhookbuddy@jobcast.net
      unsubscribeUrlFormat: https://app.webhookbuddy.com/unsubscribes/{email}?hash={hash}
      inviteUrlFormat: https://app.webhookbuddy.com/invites/{endpointId}?email={email}&hash={hash}
      smtpHost: smtp.mailgun.org
      smtpPort: 587
      smtpAuthUser: postmaster@mg.webhookbuddy.com
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
      signatureKey: ${{secrets.SIGNATURE_KEY_PROD}}
      smtpAuthPass: ${{secrets.SMTP_AUTH_PASS}}
  version_check:
    needs: run_firebase_tests
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    name: Check client version
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{steps.check.outputs.changed}} # https://github.community/t/sharing-a-variable-between-jobs/16967/14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check if version changed in client/package.json
        id: check
        uses: EndBug/version-check@v1 # https://github.com/marketplace/actions/version-check
        with:
          diff-search: true
          file-name: ./client/package.json
  publish_client_linux:
    needs: version_check
    if: ${{needs.version_check.outputs.version_changed == 'true'}}
    name: Linux
    uses: webhookbuddy/webhookbuddy/.github/workflows/publish-client.yml@dev
    with:
      runsOn: ubuntu-latest
    secrets:
      githubToken: ${{secrets.GITHUB_TOKEN}}
      firebaseKey: ${{secrets.REACT_APP_FIREBASE_KEY}}
  publish_client_macos:
    needs: version_check
    if: ${{needs.version_check.outputs.version_changed == 'true'}}
    name: macOS
    uses: webhookbuddy/webhookbuddy/.github/workflows/publish-client.yml@dev
    with:
      runsOn: macos-latest
    secrets:
      githubToken: ${{secrets.GITHUB_TOKEN}}
      firebaseKey: ${{secrets.REACT_APP_FIREBASE_KEY}}
      appleId: ${{secrets.APPLE_ID}}
      appleAppPassword: ${{secrets.APPLE_APP_PASSWORD}}
      macCerts: ${{secrets.MAC_CERTS}}
      macCertsPassword: ${{secrets.MAC_CERTS_PASSWORD}}
  publish_client_windows:
    needs: version_check
    if: ${{needs.version_check.outputs.version_changed == 'true'}}
    name: Windows
    uses: webhookbuddy/webhookbuddy/.github/workflows/publish-client.yml@dev
    with:
      runsOn: windows-latest
    secrets:
      githubToken: ${{secrets.GITHUB_TOKEN}}
      firebaseKey: ${{secrets.REACT_APP_FIREBASE_KEY}}
